CREATE TABLE [dbo].[DbQueue]
(
	[Id] BIGINT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Queue] NVARCHAR(256) NOT NULL,
	[Data] VARBINARY (MAX) NOT NULL,
	[IsBlob] BIT NOT NULL DEFAULT 0,
	[LockId] BIGINT NULL,
)
